name: luacheck
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: Roang-zero1/factorio-mod-luacheck@master
        with:
          luacheckrc_url: ""
